name: Test and Build Anchor

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test-and-build-anchor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: dapp
        run: pnpm install --frozen-lockfile

      - name: Install Anchor
        run: npm install -g @coral-xyz/anchor-cli@0.30.1

      - name: Install Solana CLI manually
        run: |
          mkdir -p ~/.local/bin
          curl -L https://github.com/solana-labs/solana/releases/download/v1.18.9/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
          tar -xvjf solana.tar.bz2
          echo "$PWD/solana-release/bin" >> $GITHUB_PATH

      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase

      - name: Set solana target cluster to local
        working-directory: dapp
        run: solana config set --url http://localhost:8899

      - name: Check solana config
        working-directory: dapp
        run: solana config get

      - name: anchor build
        working-directory: dapp
        env:
          RUSTUP_TOOLCHAIN: nightly-2025-04-14
        run: pnpm run anchor build
        shell: bash

      - name: anchor test
        working-directory: dapp
        env:
          RUSTUP_TOOLCHAIN: nightly-2025-04-14
        run: pnpm run anchor test
        shell: bash

      - name: Run Rust unit tests
        working-directory: dapp
        run: cd anchor && cargo test --lib
